general {
  lock_cmd = pidof hyprlock || hyprlock
}

listener {
  timeout = 300
  on-timeout = loginctl lock-session
}

listener {
  timeout = 240
  on-timeout = notify-send "Lock" "Your screen is about to lock in 1 minute"
}
