preload = /home/false/Pictures/Wallpapers/bg-3.png

wallpaper {
    monitor = DP-5
    path = /home/false/Pictures/Wallpapers/bg-3.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-5
    path = /home/false/Pictures/Wallpapers/bg-3.png
    fit_mode = cover
}

splash = false
